language: erlang
otp_release:
    - 17.1
before_install:
    - git clone https://github.com/elixir-lang/elixir
    - cd elixir && git checkout v1.0.2 && make && cd ..
before_script:
    - export PATH=`pwd`/elixir/bin:$PATH
    - mix local.hex --force
    - mix deps.get
script: "MIX_ENV=test mix do deps.get, test"
